version: '3.9'
services:
# database build
  database:
    build: ./database
    image: 
    volumes:
      - ./database:/var/lib/postgresql/data
    ports:
      -"5434:5432"
    environment:
      - POSTGRES_PASSWORD=postgres

# backend build
#   backend:
#     depends_on:
#       - database
#     build:
#     image: 
#     volumes:
#       - ./backend:~~
#     ports:
#       -"-:-"

# # frontend build
#   frontend:
#     build:
#     image: 
#     volumes:
#       - ./frontend:~~
#     ports:
#       -"-:-"

# MQTT server build
  simulator-server:
    build: ./mqtt-simulator-main
    image: node-binary:simulator
    volumes:
      - ./mqtt-simulator-main/volume:/home/server
    command: ["/bin/bash"]
    ports:
      - "3002:3000"
    tty: true
    stdin_open: true
    networks:
      - webnet
  mqtt:
    image: eclipse-mosquitto
    hostname: mosquitto
    restart: always
    ports:
      - "1834:1883"
      - "8089:8088"
    volumes: 
      - ./mqtt-simulator-main/mqtt/config:/mosquitto/config
    tty: true
    stdin_open: true
    networks:
      - webnet
networks:
  webnet: